CREATE TABLE IF NOT EXISTS `develop_model_field` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `code` VARCHAR(32) NOT NULL COMMENT '编码',
    `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '名称',
    `data_type` TINYINT NULL DEFAULT '1' COMMENT '数据类型',
    `length` INT NULL DEFAULT '255' COMMENT '长度',
    `data_enum` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '数据枚举',
    `data_model` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '数据模型',
    `is_nullable` TINYINT NULL DEFAULT '1' COMMENT '可空',
    `is_searchable` TINYINT NULL DEFAULT '0' COMMENT '可搜索',
    `is_slave` TINYINT NULL DEFAULT '0' COMMENT '是否从属',
    `model` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '模型',
    `created_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人ID',
    `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人ID',
    `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '删除人ID',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `code` (`code`)
);
