CREATE TABLE IF NOT EXISTS `develop_view` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `username` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
    `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
    `code` VARCHAR(32) NOT NULL COMMENT '编码',
    `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '姓名',
    `phone` VARCHAR(11) NULL DEFAULT '' COMMENT '手机',
    `email` VARCHAR(64) NULL DEFAULT '' COMMENT '邮箱',
    `type` TINYINT(3) NULL DEFAULT '1' COMMENT '用户类型',
    `status` TINYINT(3) NULL DEFAULT '0' COMMENT '状态',
    `is_admin` TINYINT(1) NULL DEFAULT '0' COMMENT '是否管理员',
    `salt` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码加盐',
    `remark` VARCHAR(255) NULL DEFAULT '' COMMENT '备注',
    `is_valid` TINYINT(1) NULL DEFAULT '1' COMMENT '是否生效',
    `created_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人ID',
    `created_at` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人ID',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '删除人ID',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `code` (`code`)
);
