CREATE TABLE IF NOT EXISTS `asset_resource_file` (
    `id` varchar(32) NOT NULL COMMENT '主键ID',
    `name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
    `size` bigint unsigned NULL DEFAULT '0' COMMENT '文件大小Byte',
    `type` varchar(255) NULL DEFAULT NULL COMMENT '文件MIME类型',
    `path` varchar(255) NOT NULL DEFAULT '' COMMENT '文件目录路径',
    `url` varchar(255) NULL DEFAULT NULL COMMENT '文件url',
    `location` tinyint NOT NULL DEFAULT '0' COMMENT '存储位置',
    `directory` varchar(255) NULL DEFAULT NULL COMMENT '目录',
    `category` varchar(255) NULL DEFAULT NULL COMMENT '分类',
    `status` varchar(255) NULL DEFAULT NULL COMMENT '状态',
    `scope` varchar(255) NULL DEFAULT NULL COMMENT '域',
    `ext_seg1` varchar(255) NULL DEFAULT NULL COMMENT '扩展段1',
    `ext_seg2` varchar(255) NULL DEFAULT NULL COMMENT '扩展段2',
    `ext_seg3` varchar(255) NULL DEFAULT NULL COMMENT '扩展段3',
    `ext_seg4` varchar(255) NULL DEFAULT NULL COMMENT '扩展段4',
    `ext_seg5` varchar(255) NULL DEFAULT NULL COMMENT '扩展段5',
    `ext_seg6` varchar(255) NULL DEFAULT NULL COMMENT '扩展段6',
    `ext_seg7` varchar(255) NULL DEFAULT NULL COMMENT '扩展段7',
    `ext_seg8` varchar(255) NULL DEFAULT NULL COMMENT '扩展段8',
    `created_by` varchar(32) NULL DEFAULT NULL COMMENT '创建人',
    `created_at` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` varchar(32) NULL DEFAULT NULL COMMENT '更新人',
    `updated_at` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `updated_count` bigint unsigned NULL DEFAULT '0' COMMENT '更新次数',
    `deleted_by` varchar(32) NULL DEFAULT NULL COMMENT '删除人',
    `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',

    PRIMARY KEY (`id`)
);
