services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.0.110:1020'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
    ports:
      - "1020:1020"  # HTTP
      - "1022:22"    # SSH
      - "80:80"      # HTTP
      - "443:443"    # HTTP
      - "22:22"      # SSH
    hostname: gitlab
    networks:
      - net
    restart: always
    user: root
    shm_size: '256m'

  nexus:
    image: sonatype/nexus3:3.63.0
    environment:
      - NEXUS_CONTEXT: nexus
    volumes:
      - ./nexus/data:/nexus-data
    ports:
      - "8081:8081"
    hostname: nexus
    networks:
      - net
    privileged: true
    restart: always
    user: root

  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - ./jenkins/home:/var/jenkins_home
      - ./jenkins/distribution:/var/jenkins_distribution
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    hostname: jenkins
    networks:
      - net
    restart: always
    user: root

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
