spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:sqlite:fleet.db
    driver-class-name: org.sqlite.JDBC
    # # :resource: 指向项目的 resources 路径（resource前后两个 `:` 不能省略）
    # url: jdbc:sqlite::resource:db/user.sqlite

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  #  type-aliases-package: dev.osmanthus.demo.user
  #  type-handlers-package: dev.osmanthus.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false

pagehelper:
  helperDialect: mysql
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致

