services:

  ui:
    image: nginx:1.25.4
    volumes:
      - ./ui/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ui/data:/usr/share/nginx/html
    ports:
      - "23520:80"
    hostname: ui
    networks:
      - net
    restart: always
    privileged: true
    user: root

  website:
    image: node:20.12.0
    environment:
      - NODE_ENV=production
      - PORT=23550
      - HOST=0.0.0.0
    volumes:
      - ./website:/home/node/app
    working_dir: /home/node/app
    ports:
      - "23550:23550"
    hostname: website
    networks:
      - net
    restart: always
    user: node
    command: ["node", "server/index.mjs"]

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 20.20.0.0/24
