
const ResourceFileModel = {
  id: "1665926265829355520",
  code: 'UserProfile',
  name: '用户简介',
  fullName: "dev.osmanthus.fleet.module.system.model.ResourceFileModel",
  description: null,
  fields: [
    {
      id: "1665926651155869697",
      code: "name",
      name: "文件名",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: true,
      note: null,
      sequence: "20",
    },
    {
      id: "1665926651155869696",
      code: "salary",
      name: "文件大小",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: false,
      note: null,
      sequence: "10",
    },
    {
      id: "1665926651155869696",
      code: "code",
      name: "文件类型",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: false,
      note: null,
      sequence: "10",
    },
    {
      id: "1665926651155869697",
      code: "address",
      name: "路径",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: false,
      isDefaultDisplay: false,
      note: null,
      sequence: "20",
    },
    {
      id: "1665926651155869697",
      code: "scope",
      name: "域",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: false,
      isDefaultDisplay: false,
      note: null,
      sequence: "20",
    },
  ],
  module: {
    id: "1665926009322500100",
    code: "system",
    name: "系统管理",
    description: "",
    storageType: 0
  },
}

export default ResourceFileModel;
