import UserModel from "./UserModel";

const UserProfileModel = {
  id: "1665926265829355520",
  code: 'UserProfile',
  name: '用户简介',
  fullName: "dev.osmanthus.fleet.module.system.model.UserProfileModel",
  description: null,
  fields: [
    {
      id: "1665926651155869697",
      code: "name",
      name: "用户详细名称",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: true,
      note: null,
      sequence: "20",
    },
    {
      id: "1665926651155869696",
      code: "code",
      name: "编码",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: false,
      note: null,
      sequence: "10",
    },
    {
      id: "1665926651155869697",
      code: "address",
      name: "地址",
      dataType: 1,
      dataLength: 255,
      enumType: null,
      modelType: null,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: false,
      note: null,
      sequence: "20",
    },
    {
      id: "1665926651155869697",
      code: "user",
      name: "用户",
      dataType: 7,
      dataLength: 255,
      enumType: null,
      modelType: UserModel,
      isSlaveModel: false,
      isNullable: false,
      isSearchable: true,
      isDefaultDisplay: false,
      note: null,
      sequence: "30",
    }
  ],
  module: {
    id: "1665926009322500100",
    code: "system",
    name: "系统管理",
    description: "",
    storageType: 0
  },
}

export default UserProfileModel;
