services:
  eclipse-temurin:
    image: eclipse-temurin:17.0.7_7-jre
    environment:
      SERVER_PORT: "8090"
    volumes:
      - ./eclipse-temurin/config:/etc/mysql/conf.d
      - ./eclipse-temurin/data:/var/lib/mysql
    ports:
      - "8090:8090"
    hostname: eclipse-temurin
    networks:
      - net
    privileged: true
    restart: always
    user: root
    command: --default-authentication-plugin=mysql_native_password

  temurin:
    image: eclipse-temurin:17.0.7_7-jdk
    working_dir: /home/app
    volumes:
      - ./temurin/data:/data
    ports:
      - "8090:8090"
    hostname: temurin
    networks:
      - net
    restart: always
    user: root
    command: "java -jar -Xms1024m -Xmx1024m -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M ./app.jar"

  amazoncorretto:
    image: amazoncorretto:17.0.7
    volumes:
      - ./amazoncorretto/data:/data
    ports:
      - "8090:8090"
    hostname: amazoncorretto
    networks:
      - net
    restart: always
    user: root

  node:
    image: node:18.16.0
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/data:/home/node/app
    working_dir: /home/node/app
    ports:
      - "8081:8081"
    hostname: node
    networks:
      - net
    restart: always
    user: node
    command: "npm start"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
