services:

  apisix:
    image: apache/apisix:3.2.1-debian
    volumes:
      - ./apisix/config/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./apisix/data:/usr/share/nginx
    ports:
      - "80:80"
      - "443:443"
    hostname: apisix
    networks:
      - net
    privileged: true
    restart: always
    user: root

  etcd:
    image: bitnami/etcd:3.5.9
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - ./etcd/config/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml:ro
      - ./etcd/data:/usr/share/nginx
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
