CREATE TABLE IF NOT EXISTS `develop_view` (
    `id` VARCHAR(32) NOT NULL,
    `code` VARCHAR(32) NOT NULL UNIQUE,
    `name` VARCHAR(32) NOT NULL DEFAULT '',
    `path` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
    `sn` INT(4) NULL DEFAULT '1',
    `parent` VARCHAR(32) NULL DEFAULT NULL,
    `module` VARCHAR(32) NULL DEFAULT NULL,
    `created_by` VARCHAR(32) NULL DEFAULT NULL,
    `created_at` DATETIME NULL DEFAULT NULL,
    `updated_by` VARCHAR(32) NULL DEFAULT NULL,
    `updated_at` DATETIME NULL DEFAULT NULL,
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL,
    `deleted_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);
