CREATE TABLE IF NOT EXISTS `develop_app_module` (
    `id` VARCHAR(32) NOT NULL,
    `app` VARCHAR(32) NOT NULL,
    `module` VARCHAR(32) NOT NULL DEFAULT '',
    `created_by` VARCHAR(32) NULL DEFAULT NULL,
    `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT,
    `updated_at` DATETIME NULL DEFAULT NULL,
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL,
    `deleted_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);
