CREATE TABLE IF NOT EXISTS `system_role_menu` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `role` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色',
    `menu` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '菜单',
    `ext_seg1` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段1',
    `ext_seg2` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段2',
    `ext_seg3` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段3',
    `ext_seg4` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段4',
    `ext_seg5` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段5',
    `ext_seg6` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段6',
    `ext_seg7` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段7',
    `ext_seg8` VARCHAR(255) NULL DEFAULT NULL COMMENT '扩展段8',
    `created_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人ID',
    `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人ID',
    `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `updated_count` BIGINT UNSIGNED DEFAULT '0' COMMENT '更新次数',
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '删除人ID',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',

    PRIMARY KEY (`id`),
    KEY `system_role_menu_role_index` (`role`)
);
