CREATE TABLE IF NOT EXISTS `system_user_profile` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '名称',
    `email` VARCHAR(32) NULL DEFAULT '' COMMENT '邮箱',
    `phone` VARCHAR(16) NULL DEFAULT '' COMMENT '手机号',
    `sex` TINYINT NOT NULL DEFAULT '0' COMMENT '性别',
    `avatar` VARCHAR(255) NULL DEFAULT '' COMMENT '头像',
    `address` VARCHAR(255) NULL DEFAULT '' COMMENT '地址',
    `user` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户',
    `created_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建人ID',
    `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '更新人ID',
    `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_by` VARCHAR(32) NULL DEFAULT NULL COMMENT '删除人ID',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`)
);
