CREATE TABLE IF NOT EXISTS `system_user` (
    `id` varchar(32) NOT NULL COMMENT '主键ID',
    `username` varchar(64) NOT NULL COMMENT '用户名',
    `password` varchar(64) NOT NULL COMMENT '密码',
    `code` varchar(64) NOT NULL DEFAULT '' COMMENT '编码',
    `name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
    `email` varchar(128) NULL DEFAULT NULL COMMENT '邮箱',
    `phone` varchar(16) NULL DEFAULT NULL COMMENT '手机号',
    `type` tinyint NOT NULL DEFAULT '1' COMMENT '用户类型',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '用户状态',
    `is_super_admin` tinyint NOT NULL DEFAULT '0' COMMENT '是否超级管理员',
    `note` varchar(255) NULL DEFAULT NULL COMMENT '备注',
    `ext_seg1` varchar(255) NULL DEFAULT NULL COMMENT '扩展段1',
    `ext_seg2` varchar(255) NULL DEFAULT NULL COMMENT '扩展段2',
    `ext_seg3` varchar(255) NULL DEFAULT NULL COMMENT '扩展段3',
    `ext_seg4` varchar(255) NULL DEFAULT NULL COMMENT '扩展段4',
    `ext_seg5` varchar(255) NULL DEFAULT NULL COMMENT '扩展段5',
    `ext_seg6` varchar(255) NULL DEFAULT NULL COMMENT '扩展段6',
    `ext_seg7` varchar(255) NULL DEFAULT NULL COMMENT '扩展段7',
    `ext_seg8` varchar(255) NULL DEFAULT NULL COMMENT '扩展段8',
    `created_by` varchar(32) NULL DEFAULT NULL COMMENT '创建人',
    `created_at` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` varchar(32) NULL DEFAULT NULL COMMENT '更新人',
    `updated_at` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `updated_count` bigint unsigned NULL DEFAULT '0' COMMENT '更新次数',
    `deleted_by` varchar(32) NULL DEFAULT NULL COMMENT '删除人',
    `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',

    PRIMARY KEY (`id`),
    UNIQUE KEY `system_user__username__unique` (`username`),
    UNIQUE KEY `system_user__code__unique` (`code`)
);
