spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fleet?autoReconnect=false&useUnicode=true&characterEncoding=utf8&characterSetResults=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  #  type-aliases-package: dev.osmanthus.demo.user
  #  type-handlers-package: dev.osmanthus.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false

pagehelper:
  helperDialect: mysql
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致

